// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA224s0Wbcbpd7idDIYrOr9THfduTIvCyA',
    appId: '1:10490607699:web:dd28743da6bbd7b142aea6',
    messagingSenderId: '10490607699',
    projectId: 'prime-play-fun',
    authDomain: 'prime-play-fun.firebaseapp.com',
    storageBucket: 'prime-play-fun.firebasestorage.app',
    measurementId: 'G-JJT7KJYBF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUx94pK4T8759B3Am2xboUsgbBOgmGbFE',
    appId: '1:10490607699:android:923c003f0b78e1f042aea6',
    messagingSenderId: '10490607699',
    projectId: 'prime-play-fun',
    storageBucket: 'prime-play-fun.firebasestorage.app',
  );
}
